# Generated by Django 4.0.3 on 2022-05-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gebruiker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('winkel', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=30)),
                ('beschrijving', models.TextField()),
                ('prijs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_URL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Orderline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aantal', models.IntegerField()),
                ('bestelling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.bestelling')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
            ],
        ),
        migrations.AddField(
            model_name='bestelling',
            name='besteller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.gebruiker'),
        ),
    ]
