# Generated by Django 4.0.3 on 2022-08-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=120)),
                ('beschrijving', models.CharField(max_length=120)),
                ('icoon', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Transactie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('datum', models.DateField()),
                ('bedrag', models.FloatField()),
                ('opmerkingen', models.CharField(blank=True, max_length=120)),
                ('groep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WalletApp.groep')),
            ],
        ),
    ]
