# Generated by Django 4.0.3 on 2022-08-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WalletApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=120)),
                ('beschrijving', models.CharField(max_length=500)),
                ('groep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WalletApp.groep')),
            ],
        ),
        migrations.AddField(
            model_name='transactie',
            name='subgroep',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='WalletApp.subgroep'),
        ),
    ]
